apiVersion: v1
kind: ConfigMap
metadata:
  name: merlai-config
  namespace: merlai
data:
  ENVIRONMENT: "production"
  MODEL_PATH: "/app/models"
  CACHE_TTL: "3600"
  MAX_CONCURRENT_REQUESTS: "10"
  LOG_LEVEL: "INFO"
  
  # Database configuration
  DATABASE_URL: "postgresql://merlai:merlai_password@postgres:5432/merlai"
  
  # Redis configuration
  REDIS_URL: "redis://redis:6379/0"
  
  # MinIO configuration
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  MINIO_BUCKET: "merlai-music"
  
  # AI Model configuration
  MODEL_BATCH_SIZE: "4"
  MODEL_MAX_LENGTH: "1024"
  MODEL_TEMPERATURE: "0.8"
  
  # MIDI configuration
  MIDI_TICKS_PER_BEAT: "480"
  MIDI_DEFAULT_VELOCITY: "64"
  MIDI_DEFAULT_DURATION: "0.5" 