name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (flake8)
        run: flake8 merlai/

      - name: Type check (mypy)
        run: mypy merlai/

      - name: Format check (black)
        run: black --check merlai/

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v

      - name: Build Docker image
        run: |
          docker build -t merlai:ci-${{ github.sha }} .

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 